// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"OnchainParser/internal/model"
	"OnchainParser/internal/model/entity"
	"context"
)

type IChain interface {
	QueryOneByChainId(ctx context.Context, chianId int32, chainName string) (rcd entity.BlockChainEntity)
	ExecInsert(ctx context.Context, chainName string, in model.BlockChainCreateInput) error
	Update(ctx context.Context, chainName string, in model.BlockChainCreateInput) error
	QueryOneByChainName(ctx context.Context, chainName string) (rcd entity.BlockChainEntity)
}

var localChain IChain

func Chain() IChain {
	if localChain == nil {
		panic("implement not found for interface IChain, forgot register?")
	}
	return localChain
}

func RegisterChain(i IChain) {
	localChain = i
}
