// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"OnchainParser/internal/model/entity"
	"context"

	"github.com/gogf/gf/v2/database/gdb"
)

type IContractSign interface {
	QueryOneByName(ctx context.Context, contractAddress string, function string, chainName string) (ent entity.ContractSignEntity, err error)
	QueryListByName(ctx context.Context, contractAddress string, beginLimt int, pageSize int, chainName string) (ent gdb.Result, err error)
	QueryListByNameAndType(ctx context.Context, contractAddress string, beginLimt int, pageSize int, dataType string, chainName string) (ent gdb.Result, err error)
	AdaptFunctionType(ftype string) string
}

var localContractSign IContractSign

func ContractSign() IContractSign {
	if localContractSign == nil {
		panic("implement not found for interface IContractSign, forgot register?")
	}
	return localContractSign
}

func RegisterContractSign(i IContractSign) {
	localContractSign = i
}
