// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"OnchainParser/internal/model"
	"OnchainParser/internal/model/entity"
	"context"
)

type IContractHistoryJob interface {
	QueryByContract(ctx context.Context, protocolCode string, contractCode string, chainName string) (rcd entity.ContractHistoryJobEntity, err error)
	Create(ctx context.Context, in model.ContractHistoryJobCreateInput, chainName string) (err error)
}

var localContractHistoryJob IContractHistoryJob

func ContractHistoryJob() IContractHistoryJob {
	if localContractHistoryJob == nil {
		panic("implement not found for interface IContractHistoryJob, forgot register?")
	}
	return localContractHistoryJob
}

func RegisterContractHistoryJob(i IContractHistoryJob) {
	localContractHistoryJob = i
}
