// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"OnchainParser/internal/model"
	"context"
)

type ITransactionLog interface {
	ExecInsert(ctx context.Context, in model.TransactionLogCreateInput, chainName string) (err error)
	ExecBatchInsert(ctx context.Context, ins []model.TransactionLogCreateInput, chainName string) (err error)
	QueryExistsByTxHashAndIndex(ctx context.Context, txHash string, logIndex int32, chainName string) (exists bool, err error)
}

var localTransactionLog ITransactionLog

func TransactionLog() ITransactionLog {
	if localTransactionLog == nil {
		panic("implement not found for interface ITransactionLog, forgot register?")
	}
	return localTransactionLog
}

func RegisterTransactionLog(i ITransactionLog) {
	localTransactionLog = i
}
