// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"OnchainParser/internal/dao/internal"
)

// internalBlockChainDao is internal type for wrapping internal DAO implements.
type internalBlockChainDao = *internal.BlockChainDao

// blockChainDao is the data access object for table block_chain.
// You can define custom methods on it to extend its functionality as you wish.
type blockChainDao struct {
	internalBlockChainDao
}

var (
	// BlockChain is globally public accessible object for table block_chain operations.
	BlockChain = blockChainDao{
		internal.NewBlockChainDao(),
	}
)

// Fill with you ideas below.
