// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"OnchainParser/internal/dao/internal"
)

// internalContractDao is internal type for wrapping internal DAO implements.
type internalContractDao = *internal.ContractDao

// contractDao is the data access object for table contract.
// You can define custom methods on it to extend its functionality as you wish.
type contractDao struct {
	internalContractDao
}

var (
	// Contract is globally public accessible object for table contract operations.
	Contract = contractDao{
		internal.NewContractDao(),
	}
)

// Fill with you ideas below.
