// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Contract is the golang structure for table Contract.
type ContractHistoryJobEntity struct {
	ProtocolCode    string `json:"protocol_code"           ` // 协议编码
	ContractCode    string `json:"contract_code"           ` // 当前交易的哈希值
	IsHistoryFinish bool   `json:"is_history_finish"       ` // 历史记录已爬取完
	UpdateTime      int32  `json:"update_time"             ` // 修改时间(时间戳)
}
