// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Contract is the golang structure for table Contract.
type ContractEntity struct {
	ProtocolCode           string `json:"protocol_code"           `             // 协议编码
	ContractCode           string `json:"contract_code"           `             // 当前交易的哈希值
	ContractAddress        string `json:"contract_address"  `                   // 合约地址
	AbiJson                string `json:"abi_json"  `                           // abi的JSON数据
	DeployHeight           int32  `json:"deploy_height"            `            // 起始区块号
	RunHeight              int32  `json:"run_height"            `               // 结束区块号
	CurrHeight             int32  `json:"curr_height"            `              // 当前爬取到的区块号
	OnceHeight             int32  `json:"once_height"            `              // 单次爬取的区块
	IsValid                bool   `json:"is_valid"            `                 // 是否已启用
	DataType               int    `json:"data_type"            `                // 数据解析类型，0:通过区块解析；1:通过event事件解析
	UpdateTime             int32  `json:"update_time"            `              // 修改时间(时间戳)
	ListenerEvent          string `json:"listener_event"            `           // 监听的事件（transfer ,approve等）
	SignedListenerEvent    string `json:"signed_listener_event"            `    // 签名好的监听事件数据
	ListenerFunction       string `json:"listener_function"            `        // 监听的方法（swap , dispreseEther等）
	SignedListenerFunction string `json:"signed_listener_function"            ` // 签名好的监听方法数据

}

type ContractViewEntity struct {
	ProtocolCode    string `json:"protocol_code"           `  // 协议编码
	ContractCode    string `json:"contract_code"           `  // 当前交易的哈希值
	ContractAddress string `json:"contract_address"  `        // 合约地址
	DeployHeight    int32  `json:"deploy_height"            ` // 起始区块号
	RunHeight       int32  `json:"run_height"               ` // 结束区块号
	CurrHeight      int32  `json:"curr_height"            `   // 当前爬取到的区块号
	OnceHeight      int32  `json:"once_height"            `   // 单次爬取的区块
	IsValid         bool   `json:"is_valid"            `      // 是否已启用
	DataType        int    `json:"data_type"            `     // 数据解析类型，0:通过区块解析；1:通过event事件解析
	UpdateTime      int32  `json:"update_time"            `   // 修改时间(时间戳)
	TaskStatus      bool   `json:"task_status"            `   // 任务是否已启动
}
