// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// transaction is the golang structure for table transaction.
type TransactionEntity struct {
	TxHash          string `json:"tx_hash"           `       // 当前交易的哈希值
	TxIndex         int32  `json:"tx_index"          `       // 签名原始数据
	Height          int32  `json:"height"            `       // 区块号
	ContractAddress string `json:"contract_address"  `       // 合约地址
	Status          int32  `json:"status"             `      // 交易状态 1:成功;0:失败
	From            string `json:"from"              `       // 交易发起者的地址
	To              string `json:"to"             	 `        // 交易接收者的地址
	Value           int64  `json:"value"             `       // 交易金额
	GasUsed         int64  `json:"gas_used"          `       // 燃料费
	GasLimit        int64  `json:"gas_limit"         `       // the gas limit in jager
	GasPrice        int64  `json:"gas_price"         `       // the gas price in jager
	TransactionFee  int64  `json:"transaction_fee"         ` // Amount paid to the miner for processing the transaction.
	CreateTime      int32  `json:"create_time"       `       // 创建时间(时间戳)
	UpdateTime      int32  `json:"update_time"       `       // 修改时间(时间戳)
	Timestamp       int32  `json:"timestamp"         `       // 交易时间(时间戳)
}
